CREATE DATABASE IF NOT EXISTS `ACTIVE_V1`;
USE `ACTIVE_V1`;

SET TIME_ZONE='-05:00';

--
-- Table structure for table `FACILITY`
--

DROP TABLE IF EXISTS `FACILITY`;
CREATE TABLE `FACILITY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEY` varchar(25) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `URL` varchar(250) NOT NULL,
  `ADDRESS` varchar(250) NOT NULL,
  `PHONE` varchar(12) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `LNG` decimal(12,10) NOT NULL,
  `LAT` decimal(12,10) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `URL` (`URL`),
  UNIQUE KEY `KEY` (`KEY`),
  UNIQUE KEY `TITLE` (`TITLE`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `CATEGORY`
--

DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE `CATEGORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEY` varchar(25) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  UNIQUE KEY `KEY` (`KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `POOL`
--

DROP TABLE IF EXISTS `POOL`;
CREATE TABLE `POOL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `LENGTH` int NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `INDOOR` tinyint(1) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


--
-- Table structure for table `type`
--

DROP TABLE IF EXISTS `TYPE`;
CREATE TABLE `TYPE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEY` varchar(25) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `CATEGORY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  UNIQUE KEY `KEY` (`KEY`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  CONSTRAINT `type_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `ACTIVITY`
--

DROP TABLE IF EXISTS `ACTIVITY`;
CREATE TABLE `ACTIVITY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL,
  `TYPE_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  KEY `TYPE_ID` (`TYPE_ID`),
  CONSTRAINT `ACTIVITY_ibfk_1` FOREIGN KEY (`TYPE_ID`) REFERENCES `TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `FACILITY_RESERVATION`
--

DROP TABLE IF EXISTS `FACILITY_RESERVATION`;
CREATE TABLE `FACILITY_RESERVATION` (
  `ID` varchar(30) NOT NULL,
  `FACILITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_ID` (`FACILITY_ID`),
  CONSTRAINT `FACILITY_RESERVATION_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `AVAILABLE_ACTIVITY`
--

DROP TABLE IF EXISTS `AVAILABLE_ACTIVITY`;
CREATE TABLE `AVAILABLE_ACTIVITY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TIME` DATETIME NOT NULL,
  `AVAILABLE` tinyint NOT NULL,
  `FACILITY_RESERVATION_ID` varchar(30) NOT NULL,
  `ACTIVITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_RESERVATION_ID` (`FACILITY_RESERVATION_ID`),
  KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `AVAILABLE_ACTIVITY_ibfk_1` FOREIGN KEY (`FACILITY_RESERVATION_ID`) REFERENCES `FACILITY_RESERVATION` (`ID`),
  CONSTRAINT `AVAILABLE_ACTIVITY_ibfk_2` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=530 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `FACILITY_ACTIVITY`
--

DROP TABLE IF EXISTS `FACILITY_ACTIVITY`;
CREATE TABLE `FACILITY_ACTIVITY` (
  `FACILITY_ID` int NOT NULL,
  `ACTIVITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FACILITY_ID`,`ACTIVITY_ID`),
  KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `FACILITY_ACTIVITY_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY` (`ID`),
  CONSTRAINT `FACILITY_ACTIVITY_ibfk_2` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


--
-- Table structure for table `FACILITY_POOL`
--

DROP TABLE IF EXISTS `FACILITY_POOL`;
CREATE TABLE `FACILITY_POOL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FACILITY_ID` int NOT NULL,
  `POOL_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_ID` (`FACILITY_ID`),
  KEY `POOL_ID` (`POOL_ID`),
  CONSTRAINT `FACILITY_POOL_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY` (`ID`),
  CONSTRAINT `FACILITY_POOL_ibfk_2` FOREIGN KEY (`POOL_ID`) REFERENCES `POOL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;